language: erlang

otp_release:
  - 18.0

sudo: false

addons:
  apt:
    packages:
      - autoconf
      - libncurses-dev
      - build-essential
      - libssl-dev
      - libwxgtk2.8-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng3
      - default-jdk
      - g++
      - xsltproc

env:
  - JOB_CMD="./otp_build all -a"
  - JOB_CMD="./otp_build autoconf && ./otp_build configure && ./otp_build boot  -a && ./otp_build release -a"
  - JOB_CMD="./otp_build autoconf && ./otp_build configure && ./otp_build boot     && ./otp_build release   "
  - JOB_CMD="./otp_build autoconf && ./otp_build configure && ./otp_build plain -a && ./otp_build release -a"
  - JOB_CMD="./otp_build autoconf && ./otp_build configure && ./otp_build plain    && ./otp_build release   "
  - JOB_CMD="./otp_build autoconf && ./otp_build configure && ./otp_build smp   -a && ./otp_build release -a"
  - JOB_CMD="./otp_build autoconf && ./otp_build configure && ./otp_build smp      && ./otp_build release   "

before_script:
  - set -e
  - export ERL_TOP=$PWD
  - export PATH=$ERL_TOP/bin:$PATH
  - export ERL_LIBS=''
  - export MAKEFLAGS=-j6
  - kerl_deactivate

script:
  - eval "$JOB_CMD"
  
after_success:
  - find . -type f -name 'beam'
  - find . -type f -name 'beam.smp'
  - ./otp_build tests && make release_docs

after_script:
  - cd $ERL_TOP/release/tests/test_server && $ERL_TOP/bin/erl -s ts install -s ts smoke_test batch -s init stop
  

